#!/bin/bash
clear
echo -e "\033[1;32mWANT TO UNINSTALLㅤ🐉ㅤOPIRAN MANAGERㅤ🐉ㅤ\033[1;33m"
read -p "Want to remove? [y/n] " resp
if [[ "$resp" = y || "$resp" = y ]];then
    apt-get purge screen -y > /dev/null 2>&1
    apt-get purge nmap -y > /dev/null 2>&1
    apt-get purge figlet -y > /dev/null 2>&1
    apt-get purge squid -y > /dev/null 2>&1
    apt-get purge squid3 -y > /dev/null 2>&1
    apt-get purge dropbear -y > /dev/null 2>&1
    apt-get purge apache2 -y > /dev/null 2>&1
    rm /bin/creatuser /bin/expcleaner /bin/sshlimiter /bin/addhost /bin/list /bin/sshmonitor /bin/help /bin/menu /bin/OpenVPN /bin/userbackup /bin/tcpspeed /bin/badvpn /bin/otimizar /bin/speedtest /bin/traffic /bin/banner /bin/limit /bin/limit /bin/passwordroot /bin/restartservices /bin/restartsystem /bin/attscript /bin/createtest /bin/socks  /bin/DropBear /bin/alterlimit /bin/alterpassword /bin/remover /bin/details /bin/changedate /bin/botssh /bin/infousers /bin/droplimiter /bin/connection /bin/version > /dev/null 2>&1
    rm -rf /etc/opiran > /dev/null 2>&1
    clear
    echo -e "\033[1;36mThank you for usingㅤ🐉ㅤOPIRAN MANAGERㅤ🐉ㅤ\033[1;33m"
    sleep 2
    cat /dev/null > ~/.bash_history && history -c && exit 0
else
    echo -e "\033[1;32CTRL+C to get out\033[1;33m"
    sleep 3
    menu
fi
